## <center>Introducción a la estadística descriptiva</center>

Es la parte de la estadística que se dedica a recolectar, ordenar, analizar y representar a un conjunto de datos, con el fin de describir apropiadamente las características de este. Calcula los parámetros estadísticos que describen el conjunto estudiado. Algunas de las herramientas que utiliza son gráficos, medidas de frecuencias, medidas de centralización, medidas de posición, medidas de dispersión, entre otras.


In [1]:
import numpy as np
import pandas as pd
from scipy import stats

# Generamos un conjunto de datos aleatorios:
datos = np.random.randn(4, 4) # Matriz 4x4
datos

array([[ 2.19464324, -0.79196312,  0.29130273,  1.84377333],
       [-1.45766187,  1.01691967,  1.16609156, -1.68622677],
       [-0.71786341,  0.80893434, -1.5225427 , -0.49459456],
       [-1.47426545, -0.83371879, -1.19203707, -0.17049824]])


### Media aritmética
Valor obtenido al sumar todos los datos y dividir el resultado entre el número total elementos. Se suele representar con la letra griega $\mu$. Si tenemos una muestra de n valores, $x_i$, la media aritmética, $\mu$, es la suma de los valores divididos por el numero de elementos; en otras palabras: 

<center> $\mu = \frac{1}{n}\sum\limits_{i}x_i$ </center>

In [2]:
media = datos.mean()
# np.mean(datos)  # <-- También
print(media)

# Media de cada fila:
print(datos.mean(axis=1))

# Media de cada columna
print(datos.mean(axis=0))

-0.188731694423
[ 0.88443904 -0.24021935 -0.48151658 -0.91762989]
[-0.36378687  0.05004302 -0.31429637 -0.12688656]


_______________________________

### Mediana
Es el valor que ocupa el lugar central de todos los datos cuando estos están ordenados de menor a mayor. Se representa con $\widetilde{x}$.

In [3]:
np.median(datos)

-0.60622898353835686

_______________________________

### Moda
Valor que tiene mayor frecuencia absoluta. Se representa con $M_0$.

In [4]:
stats.mode(datos) # Devuelve un array con la moda de cada columna y otro con la frecuencia

ModeResult(mode=array([[-1.47426545, -0.83371879, -1.5225427 , -1.68622677]]), count=array([[1, 1, 1, 1]]))

________________________________

### Desviación respecto a la media
Diferencia en valor absoluto entre cada valor de la variable estadística y la media aritmética:
<center> $D_i = | x_i - \mu | $ </center>


In [5]:
datos - media

array([[ 2.38337493, -0.60323143,  0.48003443,  2.03250502],
       [-1.26893017,  1.20565136,  1.35482326, -1.49749507],
       [-0.52913172,  0.99766603, -1.33381101, -0.30586286],
       [-1.28553376, -0.6449871 , -1.00330538,  0.01823346]])

_______________________________

### Varianza
Media aritmética del cuadrado de las desviaciones respecto a la media de una distribución estádistica. La varianza intenta describir la **dispersión de los datos**. Se representa como $\sigma^2$.
<center>$\sigma^2 = \frac{\sum\limits_{i=1}^n(x_i - \mu)^2}{n}$</center>

In [6]:
np.var(datos)

1.485698236680145

_______________________________

### Desviación estándar
Es la raíz cuadrada de la varianza. Se representa con la letra griega $\sigma$. Mide cuánto se separan los datos. Así, para cada valor se tiene una forma de saber si es muy grande, muy pequeño o normal.
<center>$ \sigma = \sqrt{\frac{\sum\limits_{i=1}^n(x_i - \mu)^2}{n}}$</center>

In [7]:
stdev = np.std(datos)
print(stdev)

1.21889221701


In [8]:
# Desviación de cada columna
np.std(datos, 0)

array([ 1.50836501,  0.86613737,  1.09414197,  1.27005447])


_______________________________

### Covarianza
Es el equivalente de la varianza aplicado a una variable bidimensional. Es la media aritmética de los productos de las desviaciones de cada una de las variables respecto a sus medias respectivas. La covarianza indica el sentido de la correlación entre las variables; Si $\sigma_xy > 0$ la correlación es directa; Si $\sigma_xy<0$ la correlación es inversa.
<center>$\sigma_{xy} = \frac{\sum\limits_{i=1}^n(x_i - \mu_x)(y_i -\mu_y)}{n}$</center>

In [9]:
np.cov(datos) # calcula matriz de covarianza

array([[ 1.93303073, -1.97463581, -0.62268436,  0.00317829],
       [-1.97463581,  2.37707087,  0.15497311, -0.2277    ],
       [-0.62268436,  0.15497311,  0.93500994,  0.17191209],
       [ 0.00317829, -0.2277    ,  0.17191209,  0.31679641]])


_______________________________

### Correlación
Trata de establecer la relación o dependencia que existe entre las dos variables que intervienen en una distribución bidimensional. Es decir, determinar si los cambios en una de las variables influyen en los cambios de la otra. En caso de que suceda, diremos que las variables están correlacionadas o que hay correlación entre ellas. La correlación es positiva cuando los valores de las variables aumenta juntos; y es negativa cuando un valor de una variable se reduce cuando el valor de la otra variable aumenta.

In [10]:
np.corrcoef(datos) # Crea matriz de correlación.

array([[ 1.        , -0.92118438, -0.46317004,  0.00406148],
       [-0.92118438,  1.        ,  0.10395064, -0.26239276],
       [-0.46317004,  0.10395064,  1.        ,  0.31586986],
       [ 0.00406148, -0.26239276,  0.31586986,  1.        ]])

In [11]:
# Correlación entre dos vectores.
np.corrcoef(datos[0], datos[1])

array([[ 1.        , -0.92118438],
       [-0.92118438,  1.        ]])


_______________________________

### Valor atípico
Un valor atípico es una observación que se aleja demasiado de la moda; esta muy lejos de la tendencia principal del resto de los datos. Pueden ser causados por errores en la recolección de datos o medidas inusuales. Generalmente se recomienda eliminarlos del conjunto de datos.